### ISSUE TITLE
Corrupt Log

### ISSUE THREAD

**Issue by bc-rb** [KelvinTegelaar/CIPP-API#137]
All of a sudden (started overnight), the alert log from the "Alerts Wizard" seems to have gotten corrupt. I have an email configured to send alerts and it's been working but now I get the following message:

The log might be corrupted. We could not retrieve the information: Cannot convert value "se status code does not indicate success: 400 (Bad Request)." to type "System.DateTime". Error: "The string 'se status code does not indicate success: 400 (Bad Request).' was not recognized as a valid DateTime. There is an unknown word starting at index '0'."

This has resulted in me getting the email every ten (10) minutes with the same message. 

Any ideas?

**Comment by KelvinTegelaar** [comment]
fixed in newer release, will be released friday.
