### ISSUE TITLE
AddMSPApp - NinjaRMM

### ISSUE THREAD

**Issue by Gvllvgher** [KelvinTegelaar/CIPP-API#175]
Hello!

I'm not sure if this is the best place to reach out, so please direct me to the right place if this is incorrect. I would like to deploy NinjaRMM to some of our tenants using the Improved Partner portal. 

In testing, I can't seem to find exactly what I need to fill out in the form below to make it go:
![image](https://user-images.githubusercontent.com/22869537/178803082-fa0f05aa-0d0c-46c1-949e-9fd959f61f22.png)

In reading/reviewing the Ninja-related files under /AddMSPApp in this repo, it appears possible that the Ninja deployment hasn't been completely implemented. 

I'm really looking for any assistance and/or documentation/information to make this work. 

Thank you!
Justin Gallagher

**Comment by KelvinTegelaar** [comment]
wrong repo, please make issues under https://github.com/kelvintegelaar/cipp

I think we'll need to assign this to someone with a bit more ninja knowledge, implementation has indeed been forgotten.

**Comment by Gvllvgher** [comment]
> I think we'll need to assign this to someone with a bit more ninja knowledge, implementation has indeed been forgotten.

Thank you, Kevin. If it's been forgotten, I won't add a feature request. I'll see if I can put a PR together.
