### ISSUE TITLE
Add Template (Transport Rules) - changing text to lowercase automatically

### ISSUE THREAD

**Issue by MC344** [KelvinTegelaar/CIPP-API#179]
Importing a JSON into the Add Template page for Transport Rules, and it appears to be changing the json to lowercase once added, so if we're setting a transport rule to append a message, it's in lowercase rather than having capital letters at certain words. There doesn't seem to be a way to change this once added.

Is it possible for this be adjusted so we can use uppercase and lowercase?

**Comment by KelvinTegelaar** [comment]
please make issues in CIPP, not CIPP API
