### ISSUE TITLE
Mail enabled security group permissions

### ISSUE THREAD

**Issue by zultanrk** [KelvinTegelaar/CIPP-API#223]
When trying to add members to a Mail-enabled security group it gives a permission error. Even with Mail-enabled security groups creating using CIPP.
![Ki0OWv6s92](https://user-images.githubusercontent.com/115669451/195455568-de2fb318-e3ea-43f3-82e9-10739cda1bd8.png)

**Comment by KelvinTegelaar** [comment]
Issues are normally only done on the CIPP branch itself. This has been solved in dev.
