### ISSUE TITLE
Create Get-Tenants function to handle tenants.cache.json

### ISSUE THREAD

**Issue by redanthrax** [KelvinTegelaar/CIPP-API#24]
Create Get-Tenants function to handle creation/loading of the tenants.cache.json file.
This will give the ability to change the functionality and simply use the function everywhere instead of trying to load the file in each azure function.

https://github.com/KelvinTegelaar/CIPP-API/blob/master/GraphHelper.psm1#51
https://github.com/KelvinTegelaar/CIPP-API/blob/master/GraphHelper.psm1#88
https://github.com/KelvinTegelaar/CIPP-API/blob/master/AddAPDevice/run.ps1#12
https://github.com/KelvinTegelaar/CIPP-API/blob/master/BestPracticeAnalyser_GetQueue/run.ps1#4
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ListMFAUsers/run.ps1#14
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ListTenants/run.ps1#12

**Comment by KelvinTegelaar** [comment]
fixed by Luke's latest changes.
