### ISSUE TITLE
Create Get-ExcludedTenants function

### ISSUE THREAD

**Issue by redanthrax** [KelvinTegelaar/CIPP-API#25]
Create the Get-ExcludedTenants function then reference that in order to create/grab excluded tenants from the ExcludedTenants file. Might want to also add Add-ExcludedTenant, Set-ExcludedTenants, and Remove-ExcludedTenant..

https://github.com/KelvinTegelaar/CIPP-API/blob/master/GraphHelper.psm1#52
https://github.com/KelvinTegelaar/CIPP-API/blob/master/GraphHelper.psm1#87
https://github.com/KelvinTegelaar/CIPP-API/blob/master/BestPracticeAnalyser_GetQueue/run.ps1#3
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ExcludeTenant/run.ps1#18
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ExcludeTenant/run.ps1#25
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ExcludeTenant/run.ps1#31
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ExcludeTenant/run.ps1#33
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ListTenants/run.ps1#10
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ListTenants/run.ps1#28

**Comment by KelvinTegelaar** [comment]
fixed by Luke's latest changes.
